// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
 await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
 );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uMjEgNDF2zBxpVlSEHS6BVOl7C_SLZk',
    appId: '1:1047406323160:web:6386d95ebac862508f3ead',
    messagingSenderId: '1047406323160',
    projectId: 'wired-brain-coffee-app',
    authDomain: 'wired-brain-coffee-app.firebaseapp.com',
    storageBucket: 'wired-brain-coffee-app.appspot.com',
    measurementId: 'G-QH6E0GPPMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAXnm77I2dKOhyygTyItNfgRQDn3S2qd4',
    appId: '1:1047406323160:android:e645a82fa4c9c1258f3ead',
    messagingSenderId: '1047406323160',
    projectId: 'wired-brain-coffee-app',
    storageBucket: 'wired-brain-coffee-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC4Y9LSuo6kkh5Bij0h1tEC-jHQJUVLsE',
    appId: '1:1047406323160:ios:6c2ee70ed3dab77b8f3ead',
    messagingSenderId: '1047406323160',
    projectId: 'wired-brain-coffee-app',
    storageBucket: 'wired-brain-coffee-app.appspot.com',
    iosClientId: '1047406323160-du17ci8lhkimljibj2tctbs26iqsng12.apps.googleusercontent.com',
    iosBundleId: 'com.marceloadrian.wiredbraincoffeflutterapplication.wiredBrainCoffeFlutterApplication',
  );
}
